# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/fixtures.yml" }

    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/cart.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/payment.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/product.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/product_review.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/product_variant.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/promotion.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/shipment.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/grids/taxon.yml" }

sylius_admin_api:
    resources:
        api_user:
            classes:
                model: "%sylius.model.admin_user.class%"

jms_serializer:
    metadata:
        directories:
            sylius-core:
                namespace_prefix: "Sylius\\Component\\Core"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/core"
            sylius-addressing:
                namespace_prefix: "Sylius\\Component\\Addressing"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/addressing"
            sylius-currency:
                namespace_prefix: "Sylius\\Component\\Currency"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/currency"
            sylius-locale:
                namespace_prefix: "Sylius\\Component\\Locale"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/locale"
            sylius-product:
                namespace_prefix: "Sylius\\Component\\Product"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/product"
            sylius-shipping:
                namespace_prefix: "Sylius\\Component\\Shipping"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/shipping"
            sylius-taxation:
                namespace_prefix: "Sylius\\Component\\Taxation"
                path: "@SyliusAdminApiBundle/Resources/config/serializer/taxation"

parameters:
    sylius.security.api_regex: "^/api/v1"
